version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      # - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./building_materials_store
    # image: polisem_docker-backend:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      db:
        condition: service_healthy  # Ждём пока БД будет готова
    ports:
      - "8000:8000"
    networks:
      - appnet
    volumes:
      - media_data:/app/media    # подключаем отдельный volume для media
    command: ["./entrypoint.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build: ./frontend
    # image: polisem_docker-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - appnet
    depends_on:
      backend:
        condition: service_started  # Ждем запуска backend

volumes:
  postgres_data:
  media_data:  # теперь volume для media явно создан

networks:
  appnet: