# Generated by Django 5.2.1 on 2025-08-01 09:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import store.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agentler',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='kategoriýa')),
            ],
            options={
                'verbose_name': 'kategoriýa',
                'verbose_name_plural': 'kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='Işgär')),
            ],
            options={
                'verbose_name': 'Işgär',
                'verbose_name_plural': 'Işgärler',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название склада')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Адрес (необязательно)')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('photo', models.ImageField(blank=True, default='images/avatar.png', null=True, upload_to='user_photos/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="Номер счета, например: '50', '90.2', '60.1'", max_length=20, unique=True)),
                ('name', models.CharField(help_text="Название счета, например: 'Касса в USD'", max_length=255)),
                ('type', models.CharField(choices=[('asset', 'Актив'), ('liability', 'Пассив'), ('income', 'Доход'), ('expense', 'Расход'), ('both', 'Актив и Пассив')], help_text='Тип счета: актив, пассив, доход, расход', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание счета (необязательно)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли счет (можно отключить старые счета)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Если счет вложенный, укажите родительский счет', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.account')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='Partneryn ady')),
                ('type', models.CharField(choices=[('klient', 'Alyjy (Покупатель)'), ('supplier', 'Üpjünçi (Поставщик)'), ('both', 'Alyjy we Üpjünçi (Покупатель и поставщик)')], default='supplier', max_length=20, verbose_name='Partneriň görnüşi')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Balans (deb/kred)')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.agent', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partnerler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Артикул (SKU)')),
                ('qr_code', models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='QR-код')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена закупки')),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Розничная цена')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оптовая цена')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('firma_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена Firma')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес (кг)')),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Объём (м³)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Длина (см)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина (см)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Высота (см)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.category', verbose_name='Категория')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.model', verbose_name='Модель')),
                ('tags', models.ManyToManyField(blank=True, to='store.tag', verbose_name='Теги')),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.unitofmeasurement', verbose_name='Базовая единица')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='FreeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество на единицу основного товара')),
                ('gift_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_as_free', to='store.product', verbose_name='Бесплатный товар')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_items', to='store.product', verbose_name='Основной товар')),
            ],
            options={
                'verbose_name': 'Бесплатный товар',
                'verbose_name_plural': 'Бесплатные товары',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания (автоматически)')),
                ('invoice_date', models.DateTimeField(verbose_name='Дата создания (фактура)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общая сумма')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('total_pay_summ', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Сумма оплаты')),
                ('isEntry', models.BooleanField(default=False, verbose_name='Проводка создана')),
                ('type_price', models.CharField(choices=[('wholesale', 'Опт'), ('retail', 'Розница')], default='wholesale', max_length=10, verbose_name='Тип продажи')),
                ('buyer', models.ForeignKey(blank=True, limit_choices_to={'type__in': ['klient', 'both']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.partner', verbose_name='Покупатель')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.employee', verbose_name='Доставил')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Расходная накладная',
                'verbose_name_plural': 'Расходные накладные',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_gift', models.BooleanField(default=False, verbose_name='Бесплатный товар')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена закупки')),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Розничная цена')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оптовая цена')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.salesinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание операции')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.salesinvoice')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Хозяйственная операция',
                'verbose_name_plural': 'Хозяйственные операции',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PriceChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('purchase', 'Цена закупки'), ('retail', 'Розничная цена'), ('wholesale', 'Оптовая цена'), ('discount', 'Цена со скидкой')], max_length=20, verbose_name='Тип цены')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Старая цена')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Новая цена')),
                ('quantity_at_change', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество на складе')),
                ('difference', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Прибыль/Убыток')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='store.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'История изменения цены',
                'verbose_name_plural': 'История изменения цен',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Дебет')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Кредит')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.account', verbose_name='Счет')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='store.transaction', verbose_name='Операция')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.warehouse')),
            ],
            options={
                'verbose_name': 'Проводка',
                'verbose_name_plural': 'Проводки',
            },
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_products', to='store.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_products', to='store.warehouse')),
            ],
            options={
                'verbose_name': 'Остаток на складе',
                'verbose_name_plural': 'Остатки на складах',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=store.models.product_image_path, verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативный текст')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'constraints': [models.UniqueConstraint(fields=('product', 'image'), name='unique_product_image')],
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(decimal_places=4, help_text='Сколько базовых единиц в 1 этой единице (напр: 1 банка = 18 литров → 18)', max_digits=10)),
                ('is_default_for_sale', models.BooleanField(default=False, help_text='Основная единица для продажи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='store.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.unitofmeasurement')),
            ],
            options={
                'verbose_name': 'ölçeg görnüşi',
                'verbose_name_plural': 'ölçeg görnüşleri',
                'constraints': [models.UniqueConstraint(fields=('product', 'unit'), name='unique_product_unit')],
            },
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['created_at'], name='store_sales_created_e76a00_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['buyer', 'created_at'], name='store_sales_buyer_i_e46329_idx'),
        ),
        migrations.AddIndex(
            model_name='pricechangehistory',
            index=models.Index(fields=['product', 'price_type'], name='store_price_product_fb9c26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouseproduct',
            unique_together={('product', 'warehouse')},
        ),
    ]
