# Generated by Django 5.2.1 on 2025-08-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_partner_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
