# Generated by Django 5.2.1 on 2025-08-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_warehouse_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='account',
        ),
    ]
