# Generated by Django 5.2.1 on 2025-08-05 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_partner_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('klient', 'Alyjy (Покупатель)'), ('supplier', 'Üpjünçi (Поставщик)'), ('both', 'Alyjy we Üpjünçi (Покупатель и поставщик)'), ('founder', 'Uchreditel (Учредитель)')], default='supplier', max_length=20, verbose_name='Partneriň görnüşi'),
        ),
        migrations.CreateModel(
            name='PartnerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer', 'Покупатель'), ('supplier', 'Поставщик'), ('founder', 'Учредитель'), ('other', 'Другое')], default='other', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.account')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_accounts', to='store.partner')),
            ],
            options={
                'unique_together': {('partner', 'account', 'role')},
            },
        ),
    ]
