# Generated by Django 5.2.1 on 2025-08-18 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0006_partner_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код операции')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.AlterField(
            model_name='partneraccount',
            name='role',
            field=models.CharField(choices=[('klient', 'Покупатель'), ('supplier', 'Поставщик'), ('both', 'Покупатель и поставщик'), ('founder', 'Учредитель')], max_length=20),
        ),
        migrations.CreateModel(
            name='PostingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postingrule_credit', to='store.account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postingrule_debit', to='store.account')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.operation')),
            ],
        ),
    ]
