# Generated by Django 5.2.1 on 2025-08-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_operation_alter_partneraccount_role_postingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingrule',
            name='partner_type',
            field=models.CharField(blank=True, choices=[('klient', 'Alyjy (Покупатель)'), ('supplier', 'Üpjünçi (Поставщик)'), ('both', 'Alyjy we Üpjünçi (Покупатель и поставщик)'), ('founder', 'Uchreditel (Учредитель)')], max_length=20, null=True, verbose_name='Тип партнёра'),
        ),
    ]
