# Generated by Django 5.2.1 on 2025-08-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_postingrule_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingrule',
            name='amount_type',
            field=models.CharField(choices=[('revenue', 'Выручка'), ('cogs', 'Себестоимость'), ('profit', 'Прибыль')], default='revenue', max_length=20),
        ),
    ]
