# Generated by Django 5.2.1 on 2025-08-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_postingrule_amount_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostingRule',
        ),
    ]
