# Generated by Django 5.2.1 on 2025-08-21 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_delete_postingrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomePostingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Тип проводки')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_type', models.CharField(choices=[('revenue', 'Выручка'), ('cogs', 'Себестоимость'), ('profit', 'Прибыль')], default='revenue', max_length=20)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postingrule_credit', to='store.account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postingrule_debit', to='store.account')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.operation')),
            ],
        ),
    ]
