# Generated by Django 5.2.1 on 2025-08-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_customepostingrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customepostingrule',
            name='content_type',
        ),
        migrations.AddField(
            model_name='customepostingrule',
            name='directory_type',
            field=models.CharField(blank=True, choices=[('klient', 'Покупатель'), ('supplier', 'Поставщик'), ('founder', 'Учредитель')], max_length=1000, null=True, verbose_name='Вид справочника'),
        ),
    ]
