# Generated by Django 5.2.1 on 2025-08-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_customepostingrule_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customepostingrule',
            options={'verbose_name': 'Правило проводки', 'verbose_name_plural': 'Правила проводок'},
        ),
        migrations.AddField(
            model_name='customepostingrule',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='customepostingrule',
            name='amount_type',
            field=models.CharField(choices=[('revenue', 'Выручка'), ('cogs', 'Себестоимость'), ('profit', 'Прибыль')], default='revenue', max_length=20, verbose_name='Тип суммы'),
        ),
        migrations.AlterField(
            model_name='customepostingrule',
            name='credit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postingrule_credit', to='store.account', verbose_name='Кредитовый счёт'),
        ),
        migrations.AlterField(
            model_name='customepostingrule',
            name='debit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postingrule_debit', to='store.account', verbose_name='Дебетовый счёт'),
        ),
        migrations.AlterField(
            model_name='customepostingrule',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='customepostingrule',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.operation', verbose_name='Операция'),
        ),
        migrations.CreateModel(
            name='WarehouseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.account', verbose_name='Счёт')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Склад → Счёт',
                'verbose_name_plural': 'Склады → Счета',
            },
        ),
    ]
