# Generated by Django 5.2.1 on 2025-07-13 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_currency_account_transaction_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.currency', verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждена'), ('canceled', 'Отменена')], default='draft', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.warehouse', verbose_name='Склад'),
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='Курс валюты')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата курса')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
