# Generated by Django 5.2.1 on 2025-08-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_customepostingrule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customepostingrule',
            name='warehouse',
        ),
    ]
