# Generated by Django 5.2.1 on 2025-08-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_customepostingrule_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customepostingrule',
            name='amount_type',
            field=models.CharField(blank=True, choices=[('revenue', 'Выручка'), ('cogs', 'Себестоимость'), ('profit', 'Прибыль'), ('pays', 'Оплата долга')], max_length=20, null=True, verbose_name='Тип суммы'),
        ),
    ]
