# Generated by Django 5.2.1 on 2025-07-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_entry_product_entry_warehouse_transaction_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturnitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='salesreturnitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='canceled_at',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='canceled_by',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='is_canceled',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='entry_type',
            field=models.CharField(choices=[('shipment', 'Отгрузка'), ('payment', 'Оплата'), ('both', 'Отгрузка и оплата')], default='shipment', max_length=10, verbose_name='Тип проводки'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждена')], default='draft', max_length=10, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='SalesReturnInvoice',
        ),
        migrations.DeleteModel(
            name='SalesReturnItem',
        ),
    ]
