# Generated by Django 5.2.1 on 2025-07-17 12:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_salesreturnitem_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='total_pay_summ',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='entry_type',
            field=models.CharField(choices=[('none', 'Не указано'), ('shipment', 'Отгрузка'), ('payment', 'Оплата'), ('both', 'Отгрузка и оплата')], default='none', max_length=10, verbose_name='Тип проводки'),
        ),
    ]
