# Generated by Django 5.2.1 on 2025-08-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_customepostingrule_amount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customepostingrule',
            name='pays_type',
            field=models.CharField(blank=True, choices=[('income', 'Приход'), ('expense', 'Расход')], max_length=20, null=True, verbose_name='Тип платежа'),
        ),
    ]
