# Generated by Django 5.2.1 on 2025-08-29 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_customepostingrule_pays_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerAccount',
        ),
    ]
