# Generated by Django 5.2.1 on 2025-07-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_salesinvoice_total_pay_summ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='isEntry',
            field=models.BooleanField(default=False, verbose_name='Проводка создана'),
        ),
    ]
