# Generated by Django 5.2.1 on 2025-07-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_salesinvoice_isentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='status',
        ),
    ]
