# Generated by Django 5.2.1 on 2025-09-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_delete_partneraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customepostingrule',
            name='amount_type',
            field=models.CharField(blank=True, choices=[('revenue', 'Продажа'), ('cogs', 'Себестоимость'), ('profit', 'Прибыль')], max_length=20, null=True, verbose_name='Тип суммы (использоваит при Фактурах)'),
        ),
        migrations.AlterField(
            model_name='customepostingrule',
            name='directory_type',
            field=models.CharField(blank=True, choices=[('klient', 'Покупатель'), ('founder', 'Учредитель')], max_length=1000, null=True, verbose_name='Вид справочника'),
        ),
        migrations.AlterField(
            model_name='customepostingrule',
            name='pays_type',
            field=models.CharField(blank=True, choices=[('income', 'Приход'), ('expense', 'Расход')], max_length=20, null=True, verbose_name='Тип платежа (использоваит при платежах)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Цена закупки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Розничная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Оптовая цена'),
        ),
    ]
