# Generated by Django 5.2.1 on 2025-07-21 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_salesinvoice_entry_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.currency'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.currency', verbose_name='Валюта'),
        ),
    ]
