# Generated by Django 5.2.1 on 2025-09-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Наименование'),
        ),
    ]
