# Generated by Django 5.2.1 on 2025-07-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_account_currency_alter_currencyrate_currency_and_more'),
    ]

    operations = [
    # сначала убираем unique_together (оно использует поле 'currency')
    migrations.AlterUniqueTogether(
        name='currencyrate',
        unique_together=None,
    ),
    # потом удаляем поле
    migrations.RemoveField(
        model_name='currencyrate',
        name='currency',
    ),
    # теперь удаляем модель
    migrations.DeleteModel(
        name='CurrencyRate',
    ),
    # и другие операции
    migrations.RemoveField(
        model_name='account',
        name='currency',
    ),
    migrations.RemoveField(
        model_name='salesinvoice',
        name='currency',
    ),
    migrations.DeleteModel(
        name='Currency',
    ),
]