# Generated by Django 5.2.1 on 2025-07-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_account_currency_remove_salesinvoice_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Остаток на складе',
                'verbose_name_plural': 'Остатки на складах',
            },
        ),
        migrations.RemoveField(
            model_name='freeproduct',
            name='gift_product',
        ),
        migrations.RemoveField(
            model_name='freeproduct',
            name='main_product',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='canceled_by',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchasereturninvoice',
            name='original_invoice',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasereturninvoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productunit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='pricechangehistory',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.warehouse', verbose_name='Склад'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['created_at'], name='store_sales_created_e76a00_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['buyer', 'created_at'], name='store_sales_buyer_i_e46329_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'image'), name='unique_product_image'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(fields=('product', 'unit'), name='unique_product_unit'),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_products', to='store.product'),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_products', to='store.warehouse'),
        ),
        migrations.DeleteModel(
            name='FreeProduct',
        ),
        migrations.DeleteModel(
            name='ProductBatch',
        ),
        migrations.DeleteModel(
            name='PurchaseInvoice',
        ),
        migrations.DeleteModel(
            name='PurchaseInvoiceItem',
        ),
        migrations.DeleteModel(
            name='PurchaseReturnInvoice',
        ),
        migrations.DeleteModel(
            name='PurchaseReturnItem',
        ),
        migrations.AlterUniqueTogether(
            name='warehouseproduct',
            unique_together={('product', 'warehouse')},
        ),
    ]
