# Generated by Django 5.2.1 on 2025-07-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_warehouseproduct_remove_freeproduct_gift_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество на единицу основного товара')),
                ('gift_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_as_free', to='store.product', verbose_name='Бесплатный товар')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_items', to='store.product', verbose_name='Основной товар')),
            ],
            options={
                'verbose_name': 'Бесплатный товар',
                'verbose_name_plural': 'Бесплатные товары',
            },
        ),
    ]
