# Generated by Django 5.2.1 on 2025-09-07 11:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Покупка'), ('return', 'Возврат')], default='purchase', max_length=10, verbose_name='Тип операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания (автоматически)')),
                ('invoice_date', models.DateTimeField(verbose_name='Дата накладной (фактура)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общая сумма')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('total_pay_summ', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Сумма оплаты')),
                ('isEntry', models.BooleanField(default=False, verbose_name='Проводка создана')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.employee', verbose_name='Принял')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.partner', verbose_name='Поставщик')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Приходная накладная',
                'verbose_name_plural': 'Приходные накладные',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.purchaseinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['created_at'], name='store_purch_created_6bb758_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['supplier', 'created_at'], name='store_purch_supplie_983a8a_idx'),
        ),
    ]
