# Generated by Django 5.2.1 on 2025-07-29 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_freeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='buyer',
            field=models.ForeignKey(blank=True, limit_choices_to={'type__in': ['klient', 'both']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.partner', verbose_name='Покупатель'),
        ),
    ]
