# Generated by Django 5.2.1 on 2025-07-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_salesinvoice_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='type_price',
            field=models.CharField(choices=[('opt', 'Опт'), ('roz', 'Розница')], default='opt', max_length=3, verbose_name='Тип продажи'),
        ),
    ]
