# Generated by Django 5.2.1 on 2025-09-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_purchaseinvoice_purchaseinvoiceitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(verbose_name='Дата операции'),
        ),
    ]
