# Generated by Django 5.2.1 on 2025-09-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=2000, unique=True, verbose_name='Partneryn ady'),
        ),
    ]
