# Generated by Django 5.2.1 on 2025-07-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_salesinvoice_type_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='type_price',
            field=models.CharField(choices=[('wholesale', 'Опт'), ('retail', 'Розница')], default='wholesale', max_length=10, verbose_name='Тип продажи'),
        ),
    ]
