# Generated by Django 5.2.1 on 2025-09-15 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_partner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда закрыл')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто закрыл')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_balances', to='store.dayclosing')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.partner')),
            ],
            options={
                'unique_together': {('closing', 'partner')},
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to='store.dayclosing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.warehouse')),
            ],
            options={
                'unique_together': {('closing', 'warehouse', 'product')},
            },
        ),
    ]
