# Generated by Django 5.2.1 on 2025-07-30 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_salesinvoice_type_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 9, 23, 39, 269495), verbose_name='Дата создания (фактура)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания (авто)'),
        ),
    ]
