# Generated by Django 5.2.1 on 2025-07-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_salesinvoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='is_gift',
            field=models.BooleanField(default=False, verbose_name='Бесплатный товар'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания (автоматически)'),
        ),
    ]
