# Generated by Django 5.2.1 on 2025-09-15 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_dayclosing_partnerbalancesnapshot_stocksnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayclosing',
            options={'ordering': ['-date'], 'verbose_name': 'Закрытие дня', 'verbose_name_plural': 'Закрытия дней'},
        ),
        migrations.AddField(
            model_name='dayclosing',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыт'),
        ),
        migrations.AlterField(
            model_name='dayclosing',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='dayclosing',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_days', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл'),
        ),
        migrations.AlterField(
            model_name='dayclosing',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='DayClosingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('close', 'Закрытие дня'), ('reopen', 'Отмена закрытия')], max_length=20, verbose_name='Действие')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина')),
                ('day_closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='store.dayclosing', verbose_name='Закрытый день')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал закрытия дня',
                'verbose_name_plural': 'Журнал закрытия дней',
                'ordering': ['-performed_at'],
            },
        ),
    ]
