# Generated by Django 5.2.1 on 2025-09-25 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_dayclosing_options_dayclosing_is_closed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='product',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awto_send', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('invoice_date', models.DateTimeField(verbose_name='Дата накладной (фактура)')),
                ('is_entry', models.BooleanField(default=False, verbose_name='Проводка создана')),
                ('partner_send', models.BooleanField(default=False)),
                ('send', models.BooleanField(default=False)),
                ('type_price', models.CharField(blank=True, choices=[('wholesale', 'Опт'), ('retail', 'Розница')], default='wholesale', max_length=50, null=True, verbose_name='Тип цены')),
                ('wozwrat_or_prihod', models.CharField(choices=[('rashod', 'Расход (Продажа)'), ('prihod', 'Приход (Закупка)'), ('wozwrat', 'Возврат')], max_length=50, verbose_name='Тип накладной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания (автоматически)')),
                ('awto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.employee', verbose_name='Доставил / Принял')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.partner', verbose_name='Партнёр')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_quantity_in_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('firma_price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('is_custom_price', models.BooleanField(default=False)),
                ('is_gift', models.BooleanField(default=False)),
                ('parent_id', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity_on_selected_warehouses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retail_price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('selected_price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('selected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_name_on_selected_warehouses', models.CharField(blank=True, max_length=50, null=True)),
                ('wholesale_price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('base_unit_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.unitofmeasurement')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='FreeItemForInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_product', models.IntegerField()),
                ('gift_product_name', models.CharField(max_length=500)),
                ('gift_product_unit_name', models.CharField(max_length=50)),
                ('quantity_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gift_product_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_product', to='store.product')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_items', to='store.invoiceitem')),
            ],
        ),
        migrations.CreateModel(
            name='UnitForInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_unit_name', models.CharField(max_length=50)),
                ('conversion_factor', models.CharField(max_length=50)),
                ('unit_id', models.IntegerField()),
                ('is_default_for_sale', models.BooleanField(default=True)),
                ('unit_name', models.CharField(max_length=50)),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='store.invoiceitem')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseForInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('warehouse_id', models.IntegerField()),
                ('warehouse_name', models.CharField(max_length=500)),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='store.invoiceitem')),
            ],
        ),
        migrations.DeleteModel(
            name='PurchaseInvoice',
        ),
        migrations.DeleteModel(
            name='PurchaseInvoiceItem',
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='store_invoi_created_bfbbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['partner', 'created_at'], name='store_invoi_partner_f2a177_idx'),
        ),
    ]
