# Generated by Django 5.2.1 on 2025-09-26 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_purchaseinvoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeitemforinvoiceitem',
            name='gift_product',
        ),
        migrations.AddField(
            model_name='invoice',
            name='entry_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сохранения с проводкой'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='entry_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_posted', to=settings.AUTH_USER_MODEL, verbose_name='Сохранил с проводкой'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания (черновик)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал (черновик)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата накладной (фактура)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='wozwrat_or_prihod',
            field=models.CharField(blank=True, choices=[('rashod', 'Расход (Продажа)'), ('prihod', 'Приход (Закупка)'), ('wozwrat', 'Возврат')], max_length=50, null=True, verbose_name='Тип накладной'),
        ),
    ]
