# Generated by Django 5.2.1 on 2025-09-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_freeitemforinvoiceitem_gift_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WarehouseForInvoiceItem',
        ),
    ]
