# Generated by Django 5.2.1 on 2025-09-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_delete_warehouseforinvoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
