# Generated by Django 5.2.1 on 2025-09-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_invoiceitem_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type_price',
            field=models.CharField(blank=True, choices=[('wholesale_price', 'Опт'), ('retail_price', 'Розница')], default='wholesale_price', max_length=50, null=True, verbose_name='Тип цены'),
        ),
    ]
