# Generated by Django 5.2.1 on 2025-09-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_invoiceitem_item_id_alter_invoice_type_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='item_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at_handle',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (черновик)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='entry_created_at_handle',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сохранения с проводкой'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at_handle',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания (черновик awto)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='entry_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сохранения с проводкой (awto)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления (awto)'),
        ),
    ]
