# Generated by Django 5.2.1 on 2025-09-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_remove_invoiceitem_item_id_invoice_created_at_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.invoice'),
        ),
    ]
