# Generated by Django 5.2.1 on 2025-09-30 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_transaction_invoice_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='invoice_new',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.invoice'),
        ),
    ]
