# Generated by Django 5.2.1 on 2025-10-02 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_remove_transaction_invoice_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayclosing',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='dayclosing',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='firma_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Цена Firma'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='purchase_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Цена закупки'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='retail_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Розничная цена'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Оптовая цена'),
        ),
        migrations.AlterField(
            model_name='dayclosing',
            name='closed_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='dayclosing',
            name='date',
            field=models.DateField(blank=True, null=True, unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dayclosinglog',
            name='action',
            field=models.CharField(blank=True, choices=[('close', 'Закрытие дня')], max_length=20, null=True, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='dayclosinglog',
            name='day_closing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='store.dayclosing'),
        ),
        migrations.AlterField(
            model_name='dayclosinglog',
            name='performed_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время действия'),
        ),
        migrations.AlterField(
            model_name='dayclosinglog',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='partnerbalancesnapshot',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='partnerbalancesnapshot',
            name='closing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_balances', to='store.dayclosing'),
        ),
        migrations.AlterField(
            model_name='partnerbalancesnapshot',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.partner'),
        ),
    ]
