# Generated by Django 5.2.1 on 2025-10-02 17:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_remove_dayclosing_is_closed_dayclosing_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Balans (deb/kred)'),
        ),
    ]
