# Generated by Django 5.2.1 on 2025-10-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_partner_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFocus', models.DateField(blank=True, null=True, verbose_name='Дата фокус')),
            ],
        ),
    ]
