# Generated by Django 5.2.1 on 2025-10-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_datefocus'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('TMT', 'TMT')], default='USD', max_length=20, null=True, verbose_name='Валюта'),
        ),
    ]
