# Generated by Django 5.2.1 on 2025-10-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_warehouse_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customepostingrule',
            name='pays_type',
        ),
        migrations.AddField(
            model_name='customepostingrule',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('TMT', 'TMT')], default='USD', max_length=20, null=True, verbose_name='Валюта'),
        ),
    ]
