# Generated by Django 5.2.1 on 2025-10-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_remove_customepostingrule_pays_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customepostingrule',
            name='amount_type',
            field=models.CharField(blank=True, choices=[('revenue', 'Продажа (цена)'), ('cogs', 'Себестоимость'), ('profit', 'Прибыль (доход цена)')], max_length=20, null=True, verbose_name='Тип суммы (использоваит при Фактурах)'),
        ),
        migrations.AlterField(
            model_name='customepostingrule',
            name='directory_type',
            field=models.CharField(blank=True, choices=[('klient', 'Покупатель'), ('founder', 'Учредитель')], max_length=1000, null=True, verbose_name='Вид партнера'),
        ),
    ]
