# Generated by Django 5.2.1 on 2025-10-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_customepostingrule_amount_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
    ]
