# Generated by Django 5.2.1 on 2025-10-09 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customepostingrule',
            name='currency_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.currency', verbose_name='Валюта FK'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='currency_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.currency', verbose_name='Валюта FK'),
        ),
    ]
