# Generated by Django 5.2.1 on 2025-10-09 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_customepostingrule_currency_fk_warehouse_currency_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='currency_fk',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.currency', verbose_name='Валюта'),
        ),
    ]
