# Generated by Django 5.2.1 on 2025-10-20 07:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_remove_customepostingrule_currency_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='balance_tmt',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Balans TMT'),
        ),
        migrations.AddField(
            model_name='partner',
            name='balance_usd',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Balans USD'),
        ),
        migrations.AddField(
            model_name='partnerbalancesnapshot',
            name='balance_tmt',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Balans TMT'),
        ),
        migrations.AddField(
            model_name='partnerbalancesnapshot',
            name='balance_usd',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Balans USD'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('klient', 'Alyjy (Покупатель)'), ('founder', 'Uchreditel (Учредитель)')], default='klient', max_length=20, verbose_name='Partneriň görnüşi'),
        ),
        migrations.AlterField(
            model_name='partnerbalancesnapshot',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=12, null=True, verbose_name='Баланс old'),
        ),
    ]
