# Generated by Django 5.2.1 on 2025-10-22 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_partner_balance_tmt_partner_balance_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='warehouse2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_to', to='store.warehouse', verbose_name='На склад (если переход со склада на склад)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_from', to='store.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='wozwrat_or_prihod',
            field=models.CharField(blank=True, choices=[('rashod', 'Расход (Продажа)'), ('prihod', 'Приход (Закупка)'), ('wozwrat', 'Возврат'), ('transfer', 'Переход')], max_length=50, null=True, verbose_name='Тип накладной'),
        ),
    ]
