# Generated by Django 5.2.1 on 2025-10-24 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_invoice_warehouse2_alter_invoice_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата Отмены проводки'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_calnceled', to=settings.AUTH_USER_MODEL, verbose_name='Отменил проводку'),
        ),
    ]
