# Generated by Django 5.2.1 on 2025-10-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_invoice_canceled_at_invoice_canceled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='canceled_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
    ]
