# Generated by Django 5.2.1 on 2025-10-29 07:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_transaction_created_at_transaction_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerbalancesnapshot',
            name='balance_60_usd',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='60 Клиент USD'),
        ),
        migrations.AddField(
            model_name='partnerbalancesnapshot',
            name='balance_62_tmt',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='62 Клиент TMT'),
        ),
        migrations.AddField(
            model_name='partnerbalancesnapshot',
            name='balance_75_usd',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='75 Учредитель USD'),
        ),
        migrations.AddField(
            model_name='partnerbalancesnapshot',
            name='balance_76_tmt',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='76 Учредитель TMT'),
        ),
    ]
