# Generated by Django 5.2.1 on 2025-11-16 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_partnerbalancesnapshot_balance_60_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.partner', verbose_name='Партнер (субконто)'),
        ),
    ]
