# Generated by Django 5.2.1 on 2025-11-26 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_entry_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.employee', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='store.trip', verbose_name='Рейс'),
        ),
        migrations.CreateModel(
            name='TripInvoiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Добавил в рейс'), ('removed', 'Удалил из рейса')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_history', to='store.invoice')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто сделал действие')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='store.trip')),
            ],
            options={
                'verbose_name': 'История накладной в рейсе',
                'verbose_name_plural': 'История накладных в рейсе',
                'ordering': ['-performed_at'],
            },
        ),
    ]
