# Generated by Django 5.2.1 on 2025-11-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('driver', 'driver'), ('warehouse_worker', 'warehouse_worker')], default='driver', max_length=50, verbose_name='Тип работника'),
        ),
    ]
