# Generated by Django 5.2.1 on 2025-11-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_handle',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('driver', 'Водитель'), ('warehouse_worker', 'Грузчик')], default='driver', max_length=50, verbose_name='Тип работника'),
        ),
    ]
