# Generated by Django 5.2.1 on 2025-12-02 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_trip_created_handle_alter_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='store.partner', verbose_name='Партнер'),
        ),
    ]
