# Generated by Django 5.2.1 on 2025-12-02 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_alter_transaction_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.partner', verbose_name='Партнер'),
        ),
    ]
