# Generated by Django 5.2.1 on 2025-12-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_alter_transaction_partner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['account'], name='store_entry_account_0b5686_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['transaction'], name='store_entry_transac_34ff56_idx'),
        ),
    ]
