# Generated by Django 5.2.1 on 2025-12-02 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_entry_store_entry_account_0b5686_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_set', to='store.partner', verbose_name='Партнер (субконто)'),
        ),
    ]
