# Generated by Django 5.2.1 on 2025-12-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_zakaz_zakazitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='created_at_handle',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='updated_at_handle',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
