# Generated by Django 5.2.1 on 2025-12-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_zakaz_created_at_handle_zakaz_updated_at_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakazitem',
            name='unit',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='created_at_handle',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='updated_at_handle',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
