# Generated by Django 5.2.1 on 2026-01-11 11:46

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_zakazitem_unit_alter_zakaz_created_at_handle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseDayAllReportExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=store.models.day_report_upload_path)),
                ('comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
    ]
