# Generated by Django 5.2.1 on 2026-01-14 15:23

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_closedayallreportexcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report_type', models.CharField(choices=[('close_day', 'Закрытие дня'), ('warehouse', 'Итоги по складу'), ('category', 'Итоги по категориям'), ('cash', 'Касса'), ('turnover', 'Обороты')], db_index=True, max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to=store.models.day_report_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('date', 'report_type')},
            },
        ),
        migrations.DeleteModel(
            name='CloseDayAllReportExcel',
        ),
    ]
