# Generated by Django 5.2.1 on 2026-01-17 16:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_dayreport_delete_closedayallreportexcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='credit',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=15, verbose_name='Кредит'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='debit',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=15, verbose_name='Дебет'),
        ),
    ]
