# Generated by Django 5.2.1 on 2026-02-01 11:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_alter_entry_credit_alter_entry_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerbalancesnapshot',
            name='balance_60_usd_credit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='partnerbalancesnapshot',
            name='balance_60_usd_debit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='partnerbalancesnapshot',
            name='balance_62_tmt_credit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='partnerbalancesnapshot',
            name='balance_62_tmt_debit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='partnerbalancesnapshot',
            name='balance_75_usd_credit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='partnerbalancesnapshot',
            name='balance_75_usd_debit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='partnerbalancesnapshot',
            name='balance_76_tmt_credit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='partnerbalancesnapshot',
            name='balance_76_tmt_debit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='dayreport',
            name='report_type',
            field=models.CharField(choices=[('OBOROT_TOWAR', 'OBOROT_TOWAR'), ('OBOROT_TOWAR_DETAIL', 'OBOROT_TOWAR_DETAIL'), ('SKIDKA', 'SKIDKA'), ('OSW', 'OSW')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerbalancesnapshot',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=20, null=True, verbose_name='Баланс old'),
        ),
        migrations.AlterField(
            model_name='partnerbalancesnapshot',
            name='balance_60_usd',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20, verbose_name='60 Клиент USD'),
        ),
        migrations.AlterField(
            model_name='partnerbalancesnapshot',
            name='balance_62_tmt',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20, verbose_name='62 Клиент TMT'),
        ),
        migrations.AlterField(
            model_name='partnerbalancesnapshot',
            name='balance_75_usd',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20, verbose_name='75 Учредитель USD'),
        ),
        migrations.AlterField(
            model_name='partnerbalancesnapshot',
            name='balance_76_tmt',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20, verbose_name='76 Учредитель TMT'),
        ),
        migrations.AlterField(
            model_name='partnerbalancesnapshot',
            name='balance_tmt',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20, verbose_name='Balans TMT'),
        ),
        migrations.AlterField(
            model_name='partnerbalancesnapshot',
            name='balance_usd',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20, verbose_name='Balans USD'),
        ),
    ]
