# Generated by Django 5.2.1 on 2026-03-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_partnerbalancesnapshot_balance_60_usd_credit_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['partner'], name='store_entry_partner_cf4426_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['product'], name='store_entry_product_4c973e_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['warehouse'], name='store_entry_warehou_869266_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='store_invoi_invoice_997782_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['warehouse'], name='store_invoi_warehou_f5d989_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['wozwrat_or_prihod'], name='store_invoi_wozwrat_efda7f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_entry'], name='store_invoi_is_entr_4e1b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['canceled_at'], name='store_invoi_cancele_430129_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['wozwrat_or_prihod', 'is_entry', 'invoice_date', 'warehouse'], name='store_invoi_wozwrat_8f0bed_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['product'], name='store_invoi_product_4dc9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='store_invoi_invoice_019444_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['product', 'invoice'], name='store_invoi_product_d7a22d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice', 'product'], name='store_invoi_invoice_ba70f4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='store_produ_brand_i_7fca7f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='store_produ_categor_6683b7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['invoice'], name='store_trans_invoice_36bb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='store_trans_date_b7f30c_idx'),
        ),
    ]
