# Generated by Django 5.2.1 on 2026-03-13 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_entry_store_entry_partner_cf4426_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_quantity', models.PositiveIntegerField()),
                ('gift_quantity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_products', to='store.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_rules', to='store.product')),
            ],
            options={
                'ordering': ['buy_quantity'],
                'unique_together': {('product', 'gift_product')},
            },
        ),
    ]
