# Generated by Django 5.2.1 on 2026-03-16 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_giftrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuantityDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_discounts', to='store.product')),
            ],
            options={
                'ordering': ['min_quantity'],
                'unique_together': {('product', 'min_quantity')},
            },
        ),
    ]
