# Generated by Django 5.2.1 on 2026-03-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_productquantitydiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='price_after_discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
